version: '3'
services:
        html:
                image: html:fix
                build:
                        context: ./html
                        args:
                                - DBHOST=sql
                                - DBNAME=$DBNAME
                                - DBUSERNAME=root
                                - DBPASSWORD=$DBPASSWORD
                ports:
                        - "443:443"  
                links:
                        - sql
        sql:
                image: sql:fix
                build:
                        context: ./sql
                        args:
                                - DBPASSWORD=$DBPASSWORD
                                - DBNAME=$DBNAME
                expose:
                        - "3306"
