version: '3'
services:
        html:
                image: orangecola/bootcamp-movie_html
                ports:
                        - "80:80"
                        - "443:443"  
                links:
                        - sql
        sql:
                image: orangecola/bootcamp-movie_sql
                expose:
                        - "3306"
